### ISSUE TITLE
Error with dotenv for python environement setup

### ISSUE THREAD

**Issue by JasonZuu** [ipolharvard/ethos-paper#2]
I encountered an issue while setting up the Python environment using _dotenv_. The error occurs during the installation process when trying to run `pip install -e .[all]`. Below is a detailed description of the problem.

## Steps to Reproduce:
1. Create a new virtual env with conda.
2. Clone the repository.
3. Install packages with `pip install -e .[all]` .

## Error Info
           Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 14, in <module>
              File "/tmp/pip-wheel-ekyqalw_/distribute_b3dddf1d18be48db93454d88fb96ce42/setuptools/__init__.py", line 2, in <module>
                from setuptools.extension import Extension, Library
              File "/tmp/pip-wheel-ekyqalw_/distribute_b3dddf1d18be48db93454d88fb96ce42/setuptools/extension.py", line 5, in <module>
                from setuptools.dist import _get_unpatched
              File "/tmp/pip-wheel-ekyqalw_/distribute_b3dddf1d18be48db93454d88fb96ce42/setuptools/dist.py", line 7, in <module>
                from setuptools.command.install import install
              File "/tmp/pip-wheel-ekyqalw_/distribute_b3dddf1d18be48db93454d88fb96ce42/setuptools/command/__init__.py", line 8, in <module>
                from setuptools.command import install_scripts
              File "/tmp/pip-wheel-ekyqalw_/distribute_b3dddf1d18be48db93454d88fb96ce42/setuptools/command/install_scripts.py", line 3, in <module>
                from pkg_resources import Distribution, PathMetadata, ensure_directory
              File "/tmp/pip-wheel-ekyqalw_/distribute_b3dddf1d18be48db93454d88fb96ce42/pkg_resources.py", line 1518, in <module>
                register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
            AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed
      
      × Encountered error while generating package metadata.
      ╰─> See above for output.
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      Traceback (most recent call last):
        File "/home/exet6188/miniconda3/envs/ethos/lib/python3.10/site-packages/setuptools/installer.py", line 102, in _fetch_build_egg_no_warn
          subprocess.check_call(cmd)
        File "/home/exet6188/miniconda3/envs/ethos/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/home/exet6188/miniconda3/envs/ethos/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpbbi0gtt1', '--quiet', 'distribute']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-6gg41f4p/dotenv_ac9c3c27204444a0bfede029a73c2ccf/setup.py", line 13, in <module>
          setup(name='dotenv',
        File "/home/exet6188/miniconda3/envs/ethos/lib/python3.10/site-packages/setuptools/__init__.py", line 116, in setup
          _install_setup_requires(attrs)
        File "/home/exet6188/miniconda3/envs/ethos/lib/python3.10/site-packages/setuptools/__init__.py", line 89, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/home/exet6188/miniconda3/envs/ethos/lib/python3.10/site-packages/setuptools/__init__.py", line 94, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/home/exet6188/miniconda3/envs/ethos/lib/python3.10/site-packages/setuptools/dist.py", line 656, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
        File "/home/exet6188/miniconda3/envs/ethos/lib/python3.10/site-packages/setuptools/installer.py", line 39, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/home/exet6188/miniconda3/envs/ethos/lib/python3.10/site-packages/pkg_resources/__init__.py", line 897, in resolve
          dist = self._resolve_dist(
        File "/home/exet6188/miniconda3/envs/ethos/lib/python3.10/site-packages/pkg_resources/__init__.py", line 933, in _resolve_dist
          dist = best[req.key] = env.best_match(
        File "/home/exet6188/miniconda3/envs/ethos/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1271, in best_match
          return self.obtain(req, installer)
        File "/home/exet6188/miniconda3/envs/ethos/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1307, in obtain
          return installer(requirement) if installer else None
        File "/home/exet6188/miniconda3/envs/ethos/lib/python3.10/site-packages/setuptools/installer.py", line 104, in _fetch_build_egg_no_warn
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/home/exet6188/miniconda3/envs/ethos/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpbbi0gtt1', '--quiet', 'distribute']' returned non-zero exit status 1.
      [end of output]

## Environment
OS: Ubuntu-22.04
Python version: 3.10.15

## Additional Information:
1. I've tried upgrading setuptools, pip, and wheel to the latest versions, but the error persists.
2. The issue seems to be related to the _dotenv_ package, which is being called during the setup.
3. I've also tried clearing the conda/pip cache, but it didn't resolve the problem.

Any help in resolving this issue would be greatly appreciated!
Thank you.

**Comment by ming-chieh-liu** [comment]
the package name for `dotenv` is actually `python-dotenv`. 
Changing it in the `pyproject.toml` works for me. 
For line 31, I changed it to `all = ["jupyter", "seaborn", "pytest", "wandb", "scikit-learn", "python-dotenv"]`

**Comment by JasonZuu** [comment]
> the package name for `dotenv` is actually `python-dotenv`. Changing it in the `pyproject.toml` works for me. For line 31, I changed it to `all = ["jupyter", "seaborn", "pytest", "wandb", "scikit-learn", "python-dotenv"]`

It works for me as well. Thank you so much!

**Comment by JasonZuu** [comment]
> the package name for `dotenv` is actually `python-dotenv`. Changing it in the `pyproject.toml` works for me. For line 31, I changed it to `all = ["jupyter", "seaborn", "pytest", "wandb", "scikit-learn", "python-dotenv"]`

It works for me as well. Thank you so much!
