### ISSUE TITLE
Wrong directory structure and file names expected by the tokenizer after train-test split

### ISSUE THREAD

**Issue by LevanBokeria** [ipolharvard/ethos-paper#6]
Hello, 

The folder and file naming produced by `data_train_test_split.py` does not seem to match that expected by the tokenizer. 

Following the README.md, I have split the data using the command `python scripts/data_train_test_split.py ethos/data/mimic-iv-2.2`. A sample of the logger output is below: 

```
(ethos) lbokeria@962-JRD76QQ6R3 ethos-paper % python scripts/data_train_test_split.py ethos/data/mimic-iv-2.2
[I 2024-11-01 15:27:40,121] Performing the split based on subject IDs 'test_size=0.10'.
[I 2024-11-01 15:27:40,122] Loading patient ids from: 'ethos/data/mimic-iv-2.2/hosp/patients.csv.gz'
[I 2024-11-01 15:27:40,127] Subject number (train/test): 45/5 (test_size=10%)
[I 2024-11-01 15:27:40,127] Found 31 subsets in the dataset directory.
[I 2024-11-01 15:27:40,128] Generating the splits in: '/Users/lbokeria/projects/health_gc/ethos-paper/ethos/data/mimic-iv-2.2_Data'
[I 2024-11-01 15:27:40,366] Saving the split ((204378, 12)): ethos/data/mimic-iv-2.2_Data/train/hosp/poe.csv.gz
[I 2024-11-01 15:27:41,356] Saving the split ((39400, 12)): ethos/data/mimic-iv-2.2_Data/test/hosp/poe.csv.gz
.
.
.
```

Following this, running the tokenizer command produces this error: 

```
(ethos) lbokeria@962-JRD76QQ6R3 ethos-paper % ethos tokenize- mimic train -v model/mimic_vocab_t4367.pkl  -j 4
[I 2024-11-01 15:29:32,026] Generating timelines for train of the MIMIC dataset
[I 2024-11-01 15:29:32,068] Loaded an exising vocabulary of size: 4367
[I 2024-11-01 15:29:32,068] Getting context data...
[W 2024-11-01 15:29:32,075] Attempted to use parquet data for efficiency, but did not find it. Falling back to CSV.
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/ethos/bin/ethos", line 8, in <module>
    sys.exit(run_cli())
  File "/Users/lbokeria/projects/health_gc/ethos-paper/ethos/cli.py", line 97, in run_cli
    cli()
  File "/opt/homebrew/anaconda3/envs/ethos/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/anaconda3/envs/ethos/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/anaconda3/envs/ethos/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/anaconda3/envs/ethos/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/anaconda3/envs/ethos/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/lbokeria/projects/health_gc/ethos-paper/ethos/commands/tokenize_.py", line 76, in tokenize_
    context_data, age_reference = get_context_data(dataset_prop, vocab, **kwargs)
  File "/Users/lbokeria/projects/health_gc/ethos-paper/ethos/tokenize/tokenization_steps.py", line 136, in get_context_data
    data = data_cls(data_prop, vocab=vocab, **kwargs)
  File "/Users/lbokeria/projects/health_gc/ethos-paper/ethos/tokenize/mimic/preprocessors.py", line 26, in __init__
    super().__init__("hosp/admissions", data_prop, use_cols=self.COLUMNS_WE_USE, **kwargs)
  File "/Users/lbokeria/projects/health_gc/ethos-paper/ethos/tokenize/base.py", line 66, in __init__
    self.df = self._load_data(
  File "/Users/lbokeria/projects/health_gc/ethos-paper/ethos/tokenize/base.py", line 122, in _load_data
    df = pd.read_csv(data_path, usecols=_use_cols, **kwargs)
  File "/opt/homebrew/anaconda3/envs/ethos/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/homebrew/anaconda3/envs/ethos/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/homebrew/anaconda3/envs/ethos/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/opt/homebrew/anaconda3/envs/ethos/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/opt/homebrew/anaconda3/envs/ethos/lib/python3.10/site-packages/pandas/io/common.py", line 765, in get_handle
    handle = gzip.GzipFile(  # type: ignore[assignment]
  File "/opt/homebrew/anaconda3/envs/ethos/lib/python3.10/gzip.py", line 174, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/Users/lbokeria/projects/health_gc/ethos-paper/ethos/data/mimic-iv-2.2_Data/mimic-iv-2.2_DataTraining/hosp/admissions_train.csv.gz'
```

Thus, the tokenizer expects `mimic-iv-2.2_Data` folder to have additional `mimic-iv-2.2_DataTraining` subfolder. And then each `csv.gz` file to have a "_train" appended to it.

The issue seems to be that the train-test splitting produces a folder structure and naming such as below: 

```
(ethos) lbokeria@962-JRD76QQ6R3 mimic-iv-2.2_Data % tree    

├── test
│   ├── hosp
│   │   ├── admissions.csv.gz
│   │   ├── d_hcpcs.csv.gz
│   │   ├── d_icd_diagnoses.csv.gz
│   │   ├── d_icd_procedures.csv.gz
│   │   ├── d_labitems.csv.gz
│   │   ├── diagnoses_icd.csv.gz
│   │   ├── drgcodes.csv.gz
│   │   ├── emar.csv.gz
│   │   ├── emar_detail.csv.gz
│   │   ├── hcpcsevents.csv.gz
│   │   ├── labevents.csv.gz
│   │   ├── microbiologyevents.csv.gz
│   │   ├── omr.csv.gz
│   │   ├── patients.csv.gz
│   │   ├── pharmacy.csv.gz
│   │   ├── poe.csv.gz
│   │   ├── poe_detail.csv.gz
│   │   ├── prescriptions.csv.gz
│   │   ├── procedures_icd.csv.gz
│   │   ├── provider.csv.gz
│   │   ├── services.csv.gz
│   │   └── transfers.csv.gz
│   └── icu
│       ├── caregiver.csv.gz
│       ├── chartevents.csv.gz
│       ├── d_items.csv.gz
│       ├── datetimeevents.csv.gz
│       ├── icustays.csv.gz
│       ├── ingredientevents.csv.gz
│       ├── inputevents.csv.gz
│       ├── outputevents.csv.gz
│       └── procedureevents.csv.gz
└── train
    ├── hosp
    │   ├── admissions.csv.gz
    │   ├── d_hcpcs.csv.gz
    │   ├── d_icd_diagnoses.csv.gz
    │   ├── d_icd_procedures.csv.gz
    │   ├── d_labitems.csv.gz
    │   ├── diagnoses_icd.csv.gz
    │   ├── drgcodes.csv.gz
    │   ├── emar.csv.gz
    │   ├── emar_detail.csv.gz
    │   ├── hcpcsevents.csv.gz
    │   ├── labevents.csv.gz
    │   ├── microbiologyevents.csv.gz
    │   ├── omr.csv.gz
    │   ├── patients.csv.gz
    │   ├── pharmacy.csv.gz
    │   ├── poe.csv.gz
    │   ├── poe_detail.csv.gz
    │   ├── prescriptions.csv.gz
    │   ├── procedures_icd.csv.gz
    │   ├── provider.csv.gz
    │   ├── services.csv.gz
    │   └── transfers.csv.gz
    └── icu
        ├── caregiver.csv.gz
        ├── chartevents.csv.gz
        ├── d_items.csv.gz
        ├── datetimeevents.csv.gz
        ├── icustays.csv.gz
        ├── ingredientevents.csv.gz
        ├── inputevents.csv.gz
        ├── outputevents.csv.gz
        └── procedureevents.csv.gz
```

**Comment by prenc** [comment]
Hi @LevanBokeria, thank you for pointing this out. I fixed the issue and tested the tokenization pipeline. Let me know if it works for you. 

Also, I would suggest a higher number of processes (`-j`) as it's only for the time token injection stage, and it's very cheap in parallelization; I usually use 50.
